#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="localai.env"

chmod +x $install_dir/local-ai

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="localai.env" --destination="$install_dir/localai.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="OpenAI alternative" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# MOVE DATA FROM OLD DATA_DIR
#=================================================
if ynh_app_upgrading_from_version_before 3.10.1~ynh1
  ynh_script_progression "Move old data directory contents for $app..."
  if [ -d "/tmp/generated/content" ]; then
    mkdir -p "$data_dir/generated/content"
    mv "/tmp/generated/content" "$data_dir/generated"
    ynh_safe_rm "/tmp/generated"
  fi
  
  if [ -d "/tmp/localai/upload" ]; then
    mkdir -p "$data_dir/upload"
    mv "/tmp/localai/upload" "$data_dir"
    ynh_safe_rm "/tmp/localai"
  fi
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="LocalAI is started and running"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
